<div class="container-fluid h-100">
	<div class="row h-100">

		<!-- Coluna Esquerda com Banner -->
		<div class="col-md-6 banner">
			<div class="row h-100 justify-content-center align-items-center">
				<div>
					<div class="communicationItem">
						<i class="fas fa-search fa-2x mr-3"></i>
						Siga o que lhe interessa.
					</div>
					<div class="communicationItem">
						<i class="fas fa-user-friends fa-2x mr-3"></i>
						Saiba sobre o que as pessoas estão falando.
					</div>
					<div class="communicationItem">
						<i class="far fa-comment fa-2x mr-3"></i>
						Participe da conversa.
					</div>
				</div>
			</div>
		</div>

		<!-- Coluna Direita com Formulário -->
		<div class="col-md-6 d-flex justify-content-center align-items-center">
			<form action="/autenticar" method="post" class="w-75">
				<div class="row border p-4">
					<div class="col-12 mb-2 text-center">
						<img src="/img/twitter_logo.png" class="text-align-center" />
						<h1 class="title">Veja o que está acontecendo no mundo agora</h1>
					</div>
					<div class="col-12 my-2">
						<input type="text" name="email" class="form-control" placeholder="E-mail">
					</div>
					<div class="col-12 mb-2">
						<input type="password" name="senha" class="form-control" placeholder="Senha">
					</div>
					<div class="col-12 text-center">
						<button type="submit" class="btn btn-primary mb-2 w-100">Entrar</button>

						<a href="/inscreverse" class="btn btn-primary mb-2 w-100">Inscrever-se</a>
					</div>
				</div>
				<?php if ($this->view->login == 'erro') { ?>
					<div class="row">
						<div class="col">
							<span class="text text-danger">Email ou senha inválido(s)!</span>
						</div>
					</div>
				<?php } ?>
			</form>
		</div>

	</div>
</div>