<div class="container">
  <!-- Centralizando a div do card no eixo vertical e horizontal -->
  <div class="d-flex justify-content-center align-items-center mt-5" style="min-height: 100vh;">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <!-- Centralizando a imagem -->
        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">

            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" name="nome" value="<?php $this->view->usuario['nome'] ?>" class="form-control"
                  placeholder="Nome">
              </div>

              <div class="form-group">
                <input type="text" name="email" value="<?= $this->view->usuario['email'] ?>" class="form-control"
                  placeholder="E-mail">
              </div>

              <div class="form-group">
                <input type="password" name="senha" value="<?= $this->view->usuario['senha'] ?>" class="form-control"
                  placeholder="Senha">
              </div>

              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o
                  Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido ·
                  Opções de Privacidade
                </small>
              </div>

              <!-- Tornando o botão full-width e centralizando o texto "Entrar" -->
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
              <div class="d-flex justify-content-center mt-2">
                <a href="/">Entrar</a>
              </div>

              <!-- Exibindo erro de cadastro caso haja algum -->
              <?php if ($this->view->erroCadastro) { ?>
                <small class="form-text text-danger">"Erro no cadastro, verifique se os campos foram preenchidos
                  corretamente."</small>
              <?php } ?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>