<!DOCTYPE html>
<html lang="pt-BR">

<!--HEAD-->
<?php require_once "components/head.phtml"; ?>

<body class="bg-light">
	<!-- Sidebar -->
	<?php require_once "components/sidebar.phtml"; ?>

	<!-- Main Content -->
	<div class="main-content">

		<!-- Top bar -->
		<?php require_once "components/topbar.phtml"; ?>

		<!--Statistics
		require_once "components/statistics.phtml";-->

		<?= $this->content() ?>


		<!-- Torneios e Próximos Jogos
		 require_once "components/torner.phtml"; -->


		<!-- RANKING 
		require_once "components/results-ranking.phtml"; -->

		<!-- GESTÃO DE JOGOS
		require_once "components/games.phtml";  -->


		<!-- Bootstrap JS e dependência Popper.js -->
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>
	</div>
</body>

</html>